cargo-features = ["edition2021"]
[package]
name = "ordo"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
parking_lot = { version = "0.11" }
crossbeam-utils = "0.8"
